// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Yat-YgGBZPATth8Qpyob_ffllWprjlg',
    appId: '1:754094927603:web:204f0497fddd981ef89186',
    messagingSenderId: '754094927603',
    projectId: 'beaver-app-370bd',
    authDomain: 'beaver-app-370bd.firebaseapp.com',
    storageBucket: 'beaver-app-370bd.firebasestorage.app',
    measurementId: 'G-033BWXMJX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEaEX3jgBqT5d0M-ms05g39SCgFruSeXs',
    appId: '1:754094927603:android:55fee4d41b57e9eaf89186',
    messagingSenderId: '754094927603',
    projectId: 'beaver-app-370bd',
    storageBucket: 'beaver-app-370bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSaa9TNdo-myt8SqCY3y-GQYXXVvAIKY',
    appId: '1:754094927603:ios:6d55f16d82ecb84ef89186',
    messagingSenderId: '754094927603',
    projectId: 'beaver-app-370bd',
    storageBucket: 'beaver-app-370bd.firebasestorage.app',
    androidClientId: '754094927603-c71p88lee2q80mv3bk70mfne94pg28u6.apps.googleusercontent.com',
    iosClientId: '754094927603-c52oe7rqob87acirk1r7sqbe7aqjrc26.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSaa9TNdo-myt8SqCY3y-GQYXXVvAIKY',
    appId: '1:754094927603:ios:6d55f16d82ecb84ef89186',
    messagingSenderId: '754094927603',
    projectId: 'beaver-app-370bd',
    storageBucket: 'beaver-app-370bd.firebasestorage.app',
    androidClientId: '754094927603-c71p88lee2q80mv3bk70mfne94pg28u6.apps.googleusercontent.com',
    iosClientId: '754094927603-c52oe7rqob87acirk1r7sqbe7aqjrc26.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Yat-YgGBZPATth8Qpyob_ffllWprjlg',
    appId: '1:754094927603:web:d80b338353cf0e6ff89186',
    messagingSenderId: '754094927603',
    projectId: 'beaver-app-370bd',
    authDomain: 'beaver-app-370bd.firebaseapp.com',
    storageBucket: 'beaver-app-370bd.firebasestorage.app',
    measurementId: 'G-B44FCLSVQM',
  );
}
